config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 6 }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit :name,
                                   :email,
                                   :password,
                                   :password_confirmation
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title page_title
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in user
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_body.html.erb
<body>
  <%= render 'layouts/header' %>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>
</body>

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header>
  <h1 class="main-title">Sample app</h1>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Users", '#' %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign out", signout_path, method: :delete%></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
      <% end %>

    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <%= render 'layouts/body' %>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1 class="title">About us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1 class="title">Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1 class="title">Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1 class="title">Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1 class="title">Update your profile</h1>

<div class="register-form">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Save changes", class: "submit" %>
  <% end %>

  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="title">Sign up</h1>
<div class="register-form">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account", class: 'submit' %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<p class="name">
  <b>Name:</b> <%= @user.name %>
</p>
<p class="email">
  <b>Email:</b> <%= @user.email %>
</p>
<p>
  <b>Gravatar:</b>
  <%= gravatar_for @user, size: 100 %>
</p>